config/routes.rb
Rex::Application.routes.draw do
  resources :dinos

  resources :document_types

  resources :documents do
    member do
      get  'add_dino'
      post 'order_dinos'
    end
  end

  root :to => 'documents#index'
end

app/models/dino.rb
class Dino < ActiveRecord::Base
  attr_accessible :content, :name

  belongs_to :original, class_name: "Dino"
  belongs_to :document

  scope :original, where(original_id: nil)

  def copies
    Dino.where(original_id: id)
  end

  def dup
    clone = super
    clone.original = self
    clone
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :name

  has_many :dinos
end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dinos_controller.rb
class DinosController < ApplicationController
  # GET /dinos
  # GET /dinos.json
  def index
    @dinos = Dino.original.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dinos }
    end
  end

  # GET /dinos/1
  # GET /dinos/1.json
  def show
    @dino = Dino.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dino }
    end
  end

  # GET /dinos/new
  # GET /dinos/new.json
  def new
    @dino = Dino.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dino }
    end
  end

  # GET /dinos/1/edit
  def edit
    @dino = Dino.find(params[:id])
  end

  # POST /dinos
  # POST /dinos.json
  def create
    @dino = Dino.new(params[:dino])

    respond_to do |format|
      if @dino.save
        format.html { redirect_to @dino, notice: 'Dino was successfully created.' }
        format.json { render json: @dino, status: :created, location: @dino }
      else
        format.html { render action: "new" }
        format.json { render json: @dino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dinos/1
  # PUT /dinos/1.json
  def update
    @dino = Dino.find(params[:id])

    respond_to do |format|
      if @dino.update_attributes(params[:dino])
        format.html { redirect_to @dino, notice: 'Dino was successfully updated.' }
        format.json { head :no_content }
        format.js   { }
      else
        format.html { render action: "edit" }
        format.json { render json: @dino.errors, status: :unprocessable_entity }
        format.js   { }
      end
    end
  end

  # DELETE /dinos/1
  # DELETE /dinos/1.json
  def destroy
    @dino = Dino.find(params[:id])
    @dino.destroy

    respond_to do |format|
      format.html { redirect_to dinos_url }
      format.json { head :no_content }
      format.js   { }
    end
  end
end

app/controllers/document_types_controller.rb
class DocumentTypesController < ApplicationController
  # GET /document_types
  # GET /document_types.json
  def index
    @document_types = DocumentType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @document_types }
    end
  end

  # GET /document_types/1
  # GET /document_types/1.json
  def show
    @document_type = DocumentType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document_type }
    end
  end

  # GET /document_types/new
  # GET /document_types/new.json
  def new
    @document_type = DocumentType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document_type }
    end
  end

  # GET /document_types/1/edit
  def edit
    @document_type = DocumentType.find(params[:id])
  end

  # POST /document_types
  # POST /document_types.json
  def create
    @document_type = DocumentType.new(params[:document_type])

    respond_to do |format|
      if @document_type.save
        format.html { redirect_to @document_type, notice: 'Document type was successfully created.' }
        format.json { render json: @document_type, status: :created, location: @document_type }
      else
        format.html { render action: "new" }
        format.json { render json: @document_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /document_types/1
  # PUT /document_types/1.json
  def update
    @document_type = DocumentType.find(params[:id])

    respond_to do |format|
      if @document_type.update_attributes(params[:document_type])
        format.html { redirect_to @document_type, notice: 'Document type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_types/1
  # DELETE /document_types/1.json
  def destroy
    @document_type = DocumentType.find(params[:id])
    @document_type.destroy

    respond_to do |format|
      format.html { redirect_to document_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  def add_dino
    @document = Document.find(params[:id])
    @original = Dino.find(params[:dino_id])
    @dino     = @original.dup

    @document.dinos.each do |dino|
      dino.update_attribute(:idx, dino.idx + 1)
    end

    @document.dinos << @dino
  end

  def order_dinos
    @document = Document.find(params[:id])

    params[:dinos].each do |id, idx|
      @document.dinos.find(id).update_attribute(:idx, idx)
    end

    head :no_content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinos_helper.rb
module DinosHelper
end

app/helpers/document_types_helper.rb
module DocumentTypesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/application/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">Rex</a>
      <div class="container">
        <ul class="nav">
          <li><%= link_to "Dinos", dinos_path  %></li>
          <li><%= link_to "Documents", documents_path  %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/dinos/_dino.html.erb
<div class="dino" id="dino-<%= dino.id %>" data-id="<%= dino.id %>" data-original-id="<%= dino.original_id %>">
  <div class="dino-actions">
    <%= link_to 'destroy', dino, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
    |
    <a data-toggle="modal" href="#modal-dino-<%=dino.id %>" >edit</a>
  </div>

  <strong class="dino-name"><%= dino.name %></strong>

  <div class="dino-content">
    <%= simple_format dino.content %>
  </div>

  <%= render '/dinos/modal_form', dino: dino %>

  <br />
</div>

app/views/dinos/_form.html.erb
<%= form_for(dino) do |f| %>
  <% if dino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dino.errors.count, "error") %> prohibited this dino from being saved:</h2>

      <ul>
      <% dino.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dinos/_modal_form.html.erb
<div id="modal-dino-<%= dino.id %>" class="modal" style="display: none;">
  <%= form_for(dino, remote: true, html: {class: 'form-vertical modal-form'}) do |f| %>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3>Modal Heading</h3>
    </div>

    <div class="modal-body">
      <fieldset>
        <div class="control-group">
          <%= f.label :name, class: 'control-label' %>
          <div class="controls">
            <%= f.text_field :name %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :content, class: 'control-label' %>
          <div class="controls">
            <%= f.text_area :content, class: 'input-xlarge', rows: 5, style: "width: 97%" %>
          </div>
        </div>
      </fieldset>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      <%= f.submit "Save Changes", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/dinos/destroy.js.erb
$("#dino-<%= @dino.id %>").fadeOut(function() {
  $(this).remove();
});

app/views/dinos/edit.html.erb
<h1>Editing dino</h1>

<%= render 'form', dino: @dino %>

<%= link_to 'Show', @dino %> |
<%= link_to 'Back', dinos_path %>

app/views/dinos/index.html.erb
<div class="page-header">
  <h1>Dinos</h1>

  <div class="page-actions">
    <%= link_to 'New Dino', new_dino_path, class: 'btn' %>
  </div>
</div>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @dinos.each do |dino| %>
    <tr>
      <td><%= dino.name %></td>
      <td><%= dino.content %></td>
      <td><%= link_to 'Show', dino %></td>
      <td><%= link_to 'Edit', edit_dino_path(dino) %></td>
      <td><%= link_to 'Destroy', dino, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/dinos/new.html.erb
<h1>New dino</h1>

<%= render 'form', dino: @dino %>

<%= link_to 'Back', dinos_path %>

app/views/dinos/show.html.erb
<div class="page-header">
  <h1><%= @dino.name %></h1>

  <div class="page-actions">
    <%= link_to 'Edit', edit_dino_path(@dino), class: 'btn' %>
  </div>
</div>

<div class="row">
  <div class="span8">
    <div class="dino-content">
      <%= simple_format @dino.content %>
    </div>
  </div>
  <div class="span4">
    <strong>Copies</strong>
    <ul>
      <% @dino.copies.each do |dino| %>
        <li><%= link_to dino.name, dino %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/dinos/update.js.erb
$("#modal-dino-<%= @dino.id %>").modal('hide')
$("#dino-<%= @dino.id %>").replaceWith("<%= j render @dino %>")
$("#dino-<%= @dino.id %>").highlight();

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/add_dino.js.erb
$('.document-dinos').prepend("<%= j render @dino %>");
$('#dino-<%= @dino.id %>').highlight();
$("#original-dino-<%= @dino.original_id %>").addClass("included");

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<div class="page-header">
  <h1>Documents</h1>

  <div class="page-actions">
    <%= link_to 'New Document', new_document_path, class: 'btn' %>
  </div>
</div>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @documents.each do |document| %>
    <tr>
      <td><%= document.name %></td>
      <td><%= link_to 'Show', document %></td>
      <td><%= link_to 'Edit', edit_document_path(document) %></td>
      <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<div class="page-header" id="document" data-id="<%= @document.id %>">
  <h1><%= @document.name %> <small>thigns</small></h1>

  <div class="page-actions">
    <%= link_to 'Edit', edit_document_path(@document), class: 'btn' %>
  </div>
</div>

<div class="row">
  <div class="span8">
    <div class="toolbar">
      <label>
        <input name="toggle-sortable" type="checkbox"> Enable Sort
      </label>
    </div>

    <div class="document-dinos sortable">
      <%= render @document.dinos.order(:idx) %>
    </div>
  </div>

  <div class="span4">
    <ul>
      <% Dino.original.each do |dino| %>
        <li id="original-dino-<%= dino.id %>">
          <%= dino.name %>
          <%= link_to "show", dino %>
          |
          <%= link_to "add", "/documents/#{@document.id}/add_dino?dino_id=#{dino.id}", remote: true %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rex" %></title>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'application/header' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>